version: 2

secret:
  ignored_matches:
    - match: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      name: hardhat test account private key

  ignored_paths:
    - '**/README.md'
    - LICENSE
    - .gitignore
    - .env